### ISSUE TITLE
og:url - To Dos

### ISSUE THREAD

**Issue by domtaylor** [CrystallizeAPI/content-commerce-boilerplate#2]
Hey guys!

Noticed this is on the To-Dos. You may find this repo useful for implementation: https://github.com/aralroca/aralroca.com/

Cheers,

Dom

**Comment by hakonkrogh** [comment]
Hi @domtaylor. Thank you for the suggestion 👍 

I just added next-seo to _app.js as en example for how to do this:
https://github.com/CrystallizeAPI/content-commerce-boilerplate/commit/87b22abec335eb1ebfef4fbadf75965459d13c30
